#! env python
import requests
import argparse
import bs4

URL = 'http://us.myprotein.com/variations.json?productId={}'
PRODUCT_ID = {
    'whey': '10852500',
    'creatine': '10852411',
}

VOUCHER_URL = 'https://us.myprotein.com/voucher-codes.list'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        'product',
        choices=PRODUCT_ID.keys(),
        default='whey',
        nargs='?',
        type=str,
    )
    parser.add_argument(
            '--vouchers',
            help='show current vouchers',
            action='store_true',
    )
    args = parser.parse_args()

    name = args.product
    id = PRODUCT_ID[name]
    flavours, pouches, sizes = get_all_products(id)

    for i in flavours:
        for k in sizes:
            get_price(id, i['id'], pouches[0]['id'], k['id'])
   
    print()

    if args.vouchers:
        get_all_vouchers()


def get_all_vouchers():
    print('Vouchers:')
    print('=' * 80)
    page = requests.get(VOUCHER_URL)
    soup = bs4.BeautifulSoup(page.content, 'html.parser')
    voucher_infos = soup.select('.voucher-info-wrapper')
    for voucher in voucher_infos:
        print(voucher.find('h2').find(text=True))
        voucher_message = voucher.select('.voucher-message')[0]
        message = voucher_message.find_all(text=True)
        message = '\n'.join(message).strip()
        print(message)
        print('-' * 80)


def get_all_products(product_id):
    combinations = requests.get(URL.format(product_id)).json()['variations']
    flavours = combinations[0]['options']
    pouches = combinations[1]['options']
    sizes = combinations[2]['options']

    return flavours, pouches, sizes


def get_price(product_id, flavour_id, package_id, size_id):
    data = {
        'selected': 3,
        'variation1': 5,
        'option1': flavour_id,
        'variation2': 6,
        'option2': package_id,
        'variation3': 7,
        'option3': size_id,
    }
    response = requests.post(URL.format(product_id), data).json()

    try:
        price = response['price'][5:]
        print('{0}\t{1}'.format(
            response['title'],
            price,
        ))
    except KeyError:
        price = None

    return price


if __name__ == '__main__':
    main()
