#! env python
import requests
import argparse

URL = 'http://us.myprotein.com/variations.json?productId={}'
PRODUCT_ID = {
    'whey': '10852500',
    'creatine': '10852411',
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        'product',
        choices=PRODUCT_ID.keys(),
        default='whey',
        nargs='?',
        type=str,
    )
    args = parser.parse_args()

    name = args.product
    id = PRODUCT_ID[name]
    flavours, pouches, sizes = get_all_products(id)

    for i in flavours:
        for k in sizes:
            get_price(id, i['id'], pouches[0]['id'], k['id'])


def get_all_products(product_id):
    combinations = requests.get(URL.format(product_id)).json()['variations']
    flavours = combinations[0]['options']
    pouches = combinations[1]['options']
    sizes = combinations[2]['options']

    return flavours, pouches, sizes


def get_price(product_id, flavour_id, package_id, size_id):
    data = {
        'selected': 3,
        'variation1': 5,
        'option1': flavour_id,
        'variation2': 6,
        'option2': package_id,
        'variation3': 7,
        'option3': size_id,
    }
    response = requests.post(URL.format(product_id), data).json()

    try:
        price = response['price'][5:]
        print('{0}\t{1}'.format(
            response['title'],
            price,
        ))
    except KeyError:
        price = None

    return price


if __name__ == '__main__':
    main()
